# Generated by Django 4.0.3 on 2022-03-11 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_place'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
