# Generated by Django 4.0.3 on 2022-03-11 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_delete_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Number',
        ),
    ]
