# Generated by Django 4.0.3 on 2022-03-11 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_slider_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='media/banner', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='bannerslider',
            name='image',
            field=models.ImageField(upload_to='media/bannersslider', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='', upload_to='media/news', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='productinner',
            name='image',
            field=models.ImageField(upload_to='media/productinner', verbose_name='Фото'),
        ),
    ]
