# Generated by Django 4.0.3 on 2022-03-14 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_banner_image_alter_bannerslider_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='LastBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='lastbanner', verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='SubInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='subinfo', verbose_name='Фото')),
            ],
        ),
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banner', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='bannerslider',
            name='image',
            field=models.ImageField(upload_to='bannersslider', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='', upload_to='news', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='productinner',
            name='image',
            field=models.ImageField(upload_to='productinner', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='slider',
            name='image',
            field=models.ImageField(upload_to='slider', verbose_name='Фото'),
        ),
    ]
