# Generated by Django 4.0.3 on 2022-03-14 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_info_lastbanner_subinfo_alter_banner_image_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LastBanner',
        ),
    ]
