# Generated by Django 4.0.3 on 2022-03-14 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_delete_lastbanner'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('image', models.ImageField(upload_to='lastbanner', verbose_name='Фото')),
            ],
        ),
    ]
