# Generated by Django 4.0.3 on 2022-03-14 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_lastbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='subinfo',
            name='foreign_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.info', verbose_name='Тема'),
        ),
    ]
