# Generated by Django 4.0.3 on 2022-03-14 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_alter_subinfo_foreign_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastbanner',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255, null='', verbose_name='Название'),
        ),
    ]
