# Generated by Django 4.0.3 on 2022-03-14 15:12

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_lastbanner_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('logo', models.FileField(blank=True, default='', upload_to='', validators=[main.validators.validate_file_extension], verbose_name='Лого')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка')),
            ],
        ),
    ]
