# Generated by Django 4.0.3 on 2022-03-15 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_footer_social'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactWall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='contactwall', verbose_name='Фото')),
            ],
        ),
    ]
