# Generated by Django 4.0.3 on 2022-03-16 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_contactwall'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.ImageField(default='', upload_to='serviceimage', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='service',
            name='title',
            field=models.CharField(default='', max_length=150, verbose_name='Название'),
        ),
    ]
