# Generated by Django 4.0.3 on 2022-03-17 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_service_description_service_image_service_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='image',
            field=models.ImageField(blank=True, default='', null='', upload_to='serviceimage', verbose_name='Фото'),
        ),
    ]
